os: osx
osx_image: xcode13.2
language: swift
script: xcodebuild clean build -project Dressed/Dressed.xcodeproj -scheme "Dressed" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.0,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
